server:
  port: 8765

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

spring:
  application:
    name: urlshortener-api-gateway
  data:
    redis:
      host: localhost
      port: 6379
      database: 4
      password:
  profiles:
    active: dev

logging:
  level:
    com.akgarg.client.authclient: INFO

auth:
  client:
    redis:
      host: localhost
      port: 6379
      pool:
        max-total: 128
        max-idle: 128
        min-idle: 16
  service:
    endpoints:
      verify-admin: /api/v1/auth/verify-admin

# noinspection SpringBootApplicationYaml
rate-limiter:
  limits:
    per-minute:
      "/api/v1/auth/**": 10
      "/api/v1/urlshortener/**": 5
      "/api/v1/statistics/**": 20
      "/api/v1/profiles/**": 20
      "/api/v1/payments/**": 20
      "/api/v1/subscriptions/**": 20
      "/api/v1/subscriptions/packs/**": 50
      "/**": 50
