server:
  port: 8765

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: urlshortener-api-gateway

logging:
  level:
    com.akgarg.client.authclient: INFO

auth:
  client:
    redis-host: localhost
    redis-port: 6379
    redis-connection-pool-max-total: 128
    redis-connection-pool-max-idle: 128
    redis-connection-pool-min-idle: 16
