server:
  port: 8765

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    healthcheck:
      enabled: true
  instance:
    status-page-url-path: /admin/management/info
    health-check-url-path: /admin/management/health

spring:
  application:
    name: urlshortener-api-gateway
  data:
    redis:
      host: localhost
      port: 6379
      database: 4
      password:
  profiles:
    active: prod

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
      base-path: /admin/management
  endpoint:
    health:
      show-details: always
    info:
      access: read_only
    metrics:
      access: read_only

logging:
  level:
    com.akgarg.client.authclient: INFO
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: DEBUG

auth:
  client:
    redis:
      host: localhost
      port: 6379
      pool:
        max-total: 128
        max-idle: 128
        min-idle: 16
  service:
    endpoints:
      verify-admin: /api/v1/auth/verify-admin

# noinspection SpringBootApplicationYaml
rate-limiter:
  limits:
    per-minute:
      "/api/v1/payments/paypal/webhook": 100
      "/api/v1/auth/**": 10
      "/api/v1/urlshortener/**": 5
      "/api/v1/statistics/**": 20
      "/api/v1/profiles/**": 20
      "/api/v1/payments/**": 20
      "/api/v1/subscriptions/**": 20
      "/api/v1/subscriptions/packs/**": 50
      "/**": 50