server:
  port: 8766

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: urlshortener-api-gateway
  data:
    redis:
      host: localhost
      port: 6379
      database: 4
      password:

logging:
  level:
    com.akgarg.client.authclient: INFO

auth:
  client:
    redis:
      host: localhost
      port: 6379
      pool:
        max-total: 128
        max-idle: 128
        min-idle: 16

rate-limiter:
  limits:
    per-minute:
      "/api/v1/auth/**": 10
      "/api/v1/urlshortener/**": 10
      "/api/v1/statistics/**": 10
      "/api/v1/profiles/**": 10
      "/api/v1/payments/**": 10
      "/**": 50
